services:
    application:
        build: .
        container_name: application_container
        ports:
            - "5050:9091"
        volumes:
            - ./logs/logFiles:/app/logs/logFiles
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            - DB_URL=${DB_URL}

    postgres:
        image: postgres:18-bookworm
        container_name: database_container
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes: 
            - todolist_pgdata:/var/lib/postgresql
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U user -d postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
volumes:
    todolist_pgdata: {}
